apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4shell-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log4shell-demo
  template:
    metadata:
      labels:
        app: log4shell-demo
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: log4shell-demo
        image: public.ecr.aws/f9n2h3p5/log4shellpub:<TAG>
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: log4shell-demo
spec:
  type: LoadBalancer
  selector:
    app: log4shell-demo
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    app: log4shell-demo
